$(document).ready(function () {
  var _PUBLIC_ = "./";
  // 图片预加载
  var _images = new Array();

  function preload() {
    for (var i = 0; i < preload.arguments.length; i++) {
      _images[i] = new Image();
      _images[i].src = preload.arguments[i]
    }
  }
  preload(
    _PUBLIC_ + "images/product1.gif",
    _PUBLIC_ + "images/product1txt.png",
    _PUBLIC_ + "images/product2.gif",
    _PUBLIC_ + "images/product2txt.png",
    _PUBLIC_ + "images/product3.gif",
    _PUBLIC_ + "images/product3txt.png",
    _PUBLIC_ + "images/dyson_logo.png",
    _PUBLIC_ + "images/grade0/1.png",
    _PUBLIC_ + "images/grade0/2.png",
    _PUBLIC_ + "images/grade0/3.png",
    _PUBLIC_ + "images/grade0/4.png",
    _PUBLIC_ + "images/grade0/5.png",
    _PUBLIC_ + "images/grade0/6.png",
    _PUBLIC_ + "images/grade0/7.png",
    _PUBLIC_ + "images/grade0/8.png",
    _PUBLIC_ + "images/grade0/9.png",
    _PUBLIC_ + "images/grade0/10.png",
    _PUBLIC_ + "images/grade0/11.png",
    _PUBLIC_ + "images/grade0/12.png",
    _PUBLIC_ + "images/grade0/13.png",
    _PUBLIC_ + "images/grade0/bg.png",
    _PUBLIC_ + "images/grade1/1.png",
    _PUBLIC_ + "images/grade1/2.png",
    _PUBLIC_ + "images/grade1/3.png",
    _PUBLIC_ + "images/grade1/4.png",
    _PUBLIC_ + "images/grade1/5.png",
    _PUBLIC_ + "images/grade1/6.png",
    _PUBLIC_ + "images/grade1/7.png",
    _PUBLIC_ + "images/grade1/8.png",
    _PUBLIC_ + "images/grade1/9.png",
    _PUBLIC_ + "images/grade1/10.png",
    _PUBLIC_ + "images/grade1/11.png",
    _PUBLIC_ + "images/grade1/12.png",
    _PUBLIC_ + "images/grade1/13.png",
    _PUBLIC_ + "images/grade1/bg.png",
    _PUBLIC_ + "images/grade2/1.png",
    _PUBLIC_ + "images/grade2/2.png",
    _PUBLIC_ + "images/grade2/3.png",
    _PUBLIC_ + "images/grade2/4.png",
    _PUBLIC_ + "images/grade2/5.png",
    _PUBLIC_ + "images/grade2/6.png",
    _PUBLIC_ + "images/grade2/7.png",
    _PUBLIC_ + "images/grade2/8.png",
    _PUBLIC_ + "images/grade2/9.png",
    _PUBLIC_ + "images/grade2/10.png",
    _PUBLIC_ + "images/grade2/11.png",
    _PUBLIC_ + "images/grade2/12.png",
    _PUBLIC_ + "images/grade2/13.png",
    _PUBLIC_ + "images/grade2/bg.png",
    _PUBLIC_ + "images/grade3/1.png",
    _PUBLIC_ + "images/grade3/2.png",
    _PUBLIC_ + "images/grade3/3.png",
    _PUBLIC_ + "images/grade3/4.png",
    _PUBLIC_ + "images/grade3/5.png",
    _PUBLIC_ + "images/grade3/6.png",
    _PUBLIC_ + "images/grade3/7.png",
    _PUBLIC_ + "images/grade3/8.png",
    _PUBLIC_ + "images/grade3/9.png",
    _PUBLIC_ + "images/grade3/10.png",
    _PUBLIC_ + "images/grade3/11.png",
    _PUBLIC_ + "images/grade3/12.png",
    _PUBLIC_ + "images/grade3/13.png",
    _PUBLIC_ + "images/grade3/bg.png",
    _PUBLIC_ + "images/grade4/1.png",
    _PUBLIC_ + "images/grade4/2.png",
    _PUBLIC_ + "images/grade4/3.png",
    _PUBLIC_ + "images/grade4/4.png",
    _PUBLIC_ + "images/grade4/5.png",
    _PUBLIC_ + "images/grade4/6.png",
    _PUBLIC_ + "images/grade4/7.png",
    _PUBLIC_ + "images/grade4/8.png",
    _PUBLIC_ + "images/grade4/9.png",
    _PUBLIC_ + "images/grade4/10.png",
    _PUBLIC_ + "images/grade4/11.png",
    _PUBLIC_ + "images/grade4/12.png",
    _PUBLIC_ + "images/grade4/13.png",
    _PUBLIC_ + "images/blessing_contain_bg.png",
    _PUBLIC_ + "images/interact_Bground.png",
    _PUBLIC_ + "images/interact_tem.png",
    _PUBLIC_ + "images/interact_wind.png",
    _PUBLIC_ + "images/slide_cursor.png",
    _PUBLIC_ + "images/choose_love.png",
    _PUBLIC_ + "images/choose_want.png",
    _PUBLIC_ + "images/blessing_footer_bag.png",
    _PUBLIC_ + "images/blessing_bg.png",
    _PUBLIC_ + "images/blessing_border_shadow.png",
    _PUBLIC_ + "images/blessing_contain_user.png",
    _PUBLIC_ + "images/blessing_footer_bag.png",
  )
})